
[workspace]
members = ["app", "async-button", "eeprom", "measurements", "monotonic", "ntc", "pwm", "ui"]
default-members = ["app"]
resolver = "2"

[workspace.dependencies]
cortex-m = {version = "0.7.7", features = ["critical-section-single-core"]}
cortex-m-rt = "0.7.5"
# stm32f4 = {version = "0.15.1", features = ["rt", "stm32f411"]}
panic-probe = { version = "0.3.2", features = ["defmt", "print-defmt"] }
rtic = {version = "2.1.2", features = [
    "cortex-m",
    # "rtic-monotonics",
    "thumbv7-backend",
]}
embedded-hal-async = "1.0.0"
defmt = "0.3.10"
defmt-rtt = "0.4.1"
rtt-target = "0.6.1"
embedded-graphics = {version = "0.8.1"}
mipidsi = "0.9.0"
embedded-hal = {version = "1.0.0"}
embedded-hal-bus = "0.3.0"
# display-interface-spi = "0.5.0"
rtic-monotonics = {version = "2.0.3", features = ["cortex-m-systick", "stm32f411ce"]}
fugit = "0.3.7"
# stm32f4xx-hal = {version = "0.22.1", features = ["stm32f411"]}
# stm32f4xx-hal = {path = "../stm32f4", features = ["stm32f411"]}
stm32f4xx-hal = {git = "https://github.com/faunel/stm32f4xx-hal", branch = "timer_input_capture", features = ["stm32f411"]}
panic-semihosting = {version = "0.6.0", features = ["exit"]}
heapless = { version = "0.8.0", features = ["ufmt"]}
ufmt = "0.2.0"
eg-seven-segment = "0.2.0"
u8g2-fonts = "0.5.1"
eeprom24x = "0.7.2"
embassy-futures = "0.1.1"
enum_dispatch = "0.3.13"
display-interface = "0.5.0"
libm = "0.2.11"
rclite = "0.2.4"
embedded-alloc = "0.6.0"
spin = "0.9.8"
stm32ral = {version = "0.8.0", default-features = false, features = ["stm32f411", "rtic"]}

[profile.release]
codegen-units = 1 # Визначає кількість одиниць генерації коду. Менше значення може покращити оптимізацію, але збільшує час компіляції.
debug = true # Визначає рівень інформації для налагодження, яка буде включена в бінарний файл. Більше значення означає більше інформації.
lto = "fat" # Визначає тип оптимізації на етапі лінкування (Link Time Optimization). "fat" означає повну LTO, "thin" - тонку LTO, а "off" - без LTO.
opt-level = "z" # Визначає рівень оптимізації. Від 0 (без оптимізації) до 3 (максимальна оптимізація), "s" для розміру, "z" для ще меншого розміру.
debug-assertions = false # Визначає, чи включати твердження для налагодження у релізній збірці. Вимкнення може покращити продуктивність.
strip = "debuginfo" # Визначає, чи видаляти інформацію для налагодження з бінарного файлу. "debuginfo" видаляє тільки налагоджувальну інформацію, "symbols" видаляє всі символи.
panic = "abort" # Визначає поведінку при паніці. "abort" завершує програму, "unwind" розмотує стек.

 