max_width = 140                     # Максимальна ширина рядка в символах
fn_call_width = 130                 # Максимальна ширина для викликів функцій
attr_fn_like_width = 90             # Максимальна ширина для атрибутів, які виглядають як виклики функцій (наприклад, #[derive(...)]
struct_lit_width = 38               # Максимальна ширина для літералів структур
struct_variant_width = 55           # Максимальна ширина для варіантів enum, які виглядають як структури
array_width = 130                   # Максимальна ширина для масивів
chain_width = 100                   # Максимальна ширина для ланцюжків викликів методів
single_line_if_else_max_width = 50 # Максимальна ширина для однорядкових конструкцій if-else
