[package]
name = "fan_controller"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fan_controller"
test = false
bench = false

[dependencies]
ui = {path = "../ui"}
eeprom = {path = "../eeprom"}
measurements = {path = "../measurements"}
async-button = {path = "../async-button"}
monotonic = {path = "../monotonic"}
ntc = {path = "../ntc"}
pwm = {path = "../pwm"}

cortex-m.workspace = true
embedded-hal.workspace = true
stm32f4xx-hal = {workspace = true}
mipidsi.workspace = true
rtic.workspace = true
embedded-hal-bus.workspace = true
# display-interface-spi.workspace = true
defmt.workspace = true
defmt-rtt.workspace = true
panic-probe = {workspace = true}
embassy-futures.workspace = true
rclite.workspace = true
embedded-alloc.workspace = true
spin.workspace = true
eeprom24x.workspace = true

stm32ral.workspace = true