[package]
name = "fan_controller"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fan_controller"
test = false
bench = false

[dependencies]
ui = {path = "../ui"}
eeprom = {path = "../eeprom"}
measurements = {path = "../measurements"}
async-button = {path = "../async-button"}
monotonic = {path = "../monotonic"}
ntc = {path = "../ntc"}

cortex-m.workspace = true
embedded-hal.workspace = true
stm32f4 = {workspace = true}
stm32f4xx-hal = {workspace = true}
heapless.workspace = true
u8g2-fonts.workspace = true
mipidsi.workspace = true
rtic = { version = "2.1.1", features = ["thumbv7-backend"] }
embedded-hal-bus.workspace = true
display-interface-spi.workspace = true
defmt.workspace = true
defmt-rtt.workspace = true
panic-probe = {workspace = true}
embassy-futures.workspace = true
rclite.workspace = true
embedded-alloc.workspace = true
spin.workspace = true